In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
from keras.layers import Dense, Activation, Flatten, Dropout, Convolution2D, MaxPooling2D
from keras.models import Sequential
from keras.utils import np_utils
import os
import cv2
from keras.utils import np_utils
from sklearn.model_selection import train_test_split 
from sklearn.utils import shuffle

Using TensorFlow backend.


In [3]:
path = './Gestures/'

In [4]:
gestures = os.listdir(path)[1:]
print gestures

['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'Nothing', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']


In [5]:
x , y = [], []

for i in gestures:
    images = os.listdir(path + i)
#     print images
    for j in images:
        if j == ".DS_Store":
            continue
        img_path = path + i + '/' + j
        img = cv2.imread(img_path, 0)
        img = cv2.resize( img, (100,100) )
        img = np.array(img)
        img = img.reshape( (100,100,1) )
        img = img/255.0
        x.append(img)
        if i == 'Nothing':
            y.append(0)
        else:
            y.append( ord(i) - 96 )

In [6]:
x = np.array(x)
y = np.array(y)
print np.unique(y)
print y

[0 1 2 3 4 5 6]
[1 1 1 ... 0 0 0]


In [7]:
x , y = shuffle(x, y, random_state=0)

In [8]:
print ord('c') - 96

3


In [9]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.30)

In [11]:
print np.unique(y_test, return_counts=True)

(array([0, 1, 2, 3, 4, 5, 6]), array([299, 314, 320, 289, 287, 293, 298]))


In [9]:
y_train = np_utils.to_categorical(y_train)
y_test = np_utils.to_categorical(y_test)
print y_train.shape
print y_test.shape

(4900, 7)
(2100, 7)


In [11]:
# model = Sequential()
# model.add(Flatten(input_shape=(100, 100, 1)))
# model.add(Dense(128))
# model.add(Activation('relu'))
# model.add(Dense(64))
# model.add( Dropout(0.4) )
# model.add(Activation('relu'))
# model.add(Dense(7))
# model.add(Activation('softmax'))

# model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten_1 (Flatten)          (None, 10000)             0         
_________________________________________________________________
dense_1 (Dense)              (None, 128)               1280128   
_________________________________________________________________
activation_1 (Activation)    (None, 128)               0         
_________________________________________________________________
dense_2 (Dense)              (None, 64)                8256      
_________________________________________________________________
dropout_1 (Dropout)          (None, 64)                0         
_________________________________________________________________
activation_2 (Activation)    (None, 64)                0         
_________________________________________________________________
dense_3 (Dense)              (None, 7)                 455       
__________

In [21]:
model = Sequential()

model.add( Convolution2D(32, 3, 3, input_shape = (100,100,1) ) )
model.add( Activation('relu') )

model.add( Convolution2D( 64,3,3 ) )
model.add( Activation('relu') )

model.add( MaxPooling2D( pool_size=(2,2) ) )

model.add( Convolution2D( 16, 3, 3 ) )
model.add( Activation('relu') )

model.add( Flatten() )

model.add( Dropout(0.25) )
model.add( Dense(7) )

model.add( Activation('softmax') )

model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_7 (Conv2D)            (None, 98, 98, 32)        320       
_________________________________________________________________
activation_11 (Activation)   (None, 98, 98, 32)        0         
_________________________________________________________________
conv2d_8 (Conv2D)            (None, 96, 96, 64)        18496     
_________________________________________________________________
activation_12 (Activation)   (None, 96, 96, 64)        0         
_________________________________________________________________
max_pooling2d_3 (MaxPooling2 (None, 48, 48, 64)        0         
_________________________________________________________________
conv2d_9 (Conv2D)            (None, 46, 46, 16)        9232      
_________________________________________________________________
activation_13 (Activation)   (None, 46, 46, 16)        0         
__________

/usr/local/lib/python2.7/site-packages/ipykernel_launcher.py:3: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(32, (3, 3), input_shape=(100, 100,...)`
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python2.7/site-packages/ipykernel_launcher.py:6: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(64, (3, 3))`
  
/usr/local/lib/python2.7/site-packages/ipykernel_launcher.py:11: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(16, (3, 3))`
  # This is added back by InteractiveShellApp.init_path()


In [22]:
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [23]:
model.fit( x_train, y_train, validation_data=( x_test, y_test ), shuffle=True, epochs=10 )

Train on 4900 samples, validate on 2100 samples
Epoch 1/10
4900/4900 [==============================] - 260s 53ms/step - loss: 0.4540 - acc: 0.8612 - val_loss: 0.0996 - val_acc: 0.9743
Epoch 2/10
4900/4900 [==============================] - 258s 53ms/step - loss: 0.0560 - acc: 0.9835 - val_loss: 0.0240 - val_acc: 0.9948
Epoch 3/10
4900/4900 [==============================] - 280s 57ms/step - loss: 0.0119 - acc: 0.9967 - val_loss: 0.0299 - val_acc: 0.9905
Epoch 4/10
4900/4900 [==============================] - 260s 53ms/step - loss: 0.0072 - acc: 0.9976 - val_loss: 0.0333 - val_acc: 0.9924
Epoch 5/10
4900/4900 [==============================] - 267s 54ms/step - loss: 0.0196 - acc: 0.9949 - val_loss: 0.0116 - val_acc: 0.9957
Epoch 6/10
4900/4900 [==============================] - 260s 53ms/step - loss: 0.0012 - acc: 1.0000 - val_loss: 0.0053 - val_acc: 0.9981
Epoch 7/10
4900/4900 [==============================] - 264s 54ms/step - loss: 2.3355e-04 - acc: 1.0000 - val_loss: 0.0055 - val_a

In [25]:
model.save('Gesture_Recognizing.h5')