In [47]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
from keras.layers import Dense, Activation, Flatten, Dropout, Convolution2D, MaxPooling2D
from keras.models import Sequential
from keras.utils import np_utils
import os
import cv2
from keras.utils import np_utils
from sklearn.model_selection import train_test_split 
from sklearn.utils import shuffle

In [48]:
path = './Gestures/'

In [49]:
gestures = os.listdir(path)[1:]
print gestures

['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'ily', 'j', 'k', 'l', 'm', 'n', 'Nothing', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']


In [50]:
x , y = [], []

for i in gestures:
    images = os.listdir(path + i)
#     print images
    for j in images:
        if j == ".DS_Store":
            continue
        img_path = path + i + '/' + j
        img = cv2.imread(img_path, 0)
        img = cv2.resize( img, (100,100) )
        img = np.array(img)
        img = img.reshape( (100,100,1) )
        img = img/255.0
        x.append(img)
        if i == 'Nothing':
            y.append(0)
        elif i == 'ily':
            y.append(30)
        else:
            y.append( ord(i) - 96 )

In [51]:
x = np.array(x)
y = np.array(y)
print np.unique(y)
print y

[ 0  5  8 12 15 30]
[ 5  5  5 ... 15 15 15]


In [52]:
x , y = shuffle(x, y, random_state=0)

In [53]:
print ord('c') - 96

3


In [54]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.30)

In [55]:
print np.unique(y_test, return_counts=True)

(array([ 0,  5,  8, 12, 15, 30]), array([304, 307, 290, 288, 298, 313]))


In [56]:
y_train = np_utils.to_categorical(y_train)
y_test = np_utils.to_categorical(y_test)
print y_train.shape
print y_test.shape

(4200, 31)
(1800, 31)


In [61]:
model = Sequential()
model.add(Flatten(input_shape=(100, 100, 1)))
model.add(Dense(128))
model.add(Activation('relu'))
model.add(Dense(64))
model.add( Dropout(0.4) )
model.add(Activation('relu'))
model.add(Dense(31))
model.add(Activation('softmax'))

model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten_7 (Flatten)          (None, 10000)             0         
_________________________________________________________________
dense_17 (Dense)             (None, 128)               1280128   
_________________________________________________________________
activation_20 (Activation)   (None, 128)               0         
_________________________________________________________________
dense_18 (Dense)             (None, 64)                8256      
_________________________________________________________________
dropout_7 (Dropout)          (None, 64)                0         
_________________________________________________________________
activation_21 (Activation)   (None, 64)                0         
_________________________________________________________________
dense_19 (Dense)             (None, 31)                2015      
__________

In [63]:
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [64]:
model.fit( x_train, y_train, validation_data=( x_test, y_test ), shuffle=True, epochs=10 )

Train on 4200 samples, validate on 1800 samples
Epoch 1/10
4200/4200 [==============================] - 5s 1ms/step - loss: 0.4183 - acc: 0.8829 - val_loss: 0.0472 - val_acc: 0.9889
Epoch 2/10
4200/4200 [==============================] - 5s 1ms/step - loss: 0.0701 - acc: 0.9812 - val_loss: 0.0201 - val_acc: 0.9944
Epoch 3/10
4200/4200 [==============================] - 5s 1ms/step - loss: 0.0398 - acc: 0.9871 - val_loss: 0.0057 - val_acc: 0.9983
Epoch 4/10
4200/4200 [==============================] - 5s 1ms/step - loss: 0.0150 - acc: 0.9948 - val_loss: 0.0440 - val_acc: 0.9806
Epoch 5/10
4200/4200 [==============================] - 5s 1ms/step - loss: 0.0150 - acc: 0.9960 - val_loss: 0.0113 - val_acc: 0.9950
Epoch 6/10
4200/4200 [==============================] - 5s 1ms/step - loss: 0.0109 - acc: 0.9962 - val_loss: 0.0151 - val_acc: 0.9956
Epoch 7/10
4200/4200 [==============================] - 5s 1ms/step - loss: 0.0040 - acc: 0.9990 - val_loss: 1.6753e-04 - val_acc: 1.0000
Epoch 8/10

In [65]:
model.save('Gesture_Recognizing.h5')